name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Add Nova Authorization
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_LICENSE_KEY }}"

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Boot Laravel application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan --version

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
